apiVersion: v1
kind: Namespace
metadata:
  name: demo-ee
  labels:
    name: demo-ee
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-service
  namespace: demo-ee
spec:
  replicas: 2  # 启动 2 个副本
  selector:
    matchLabels:
      app: demo-springmvc-app
  template:
    metadata:
      labels:
        app: demo-springmvc-app
    spec:
      containers:
        - name: demo-springmvc-app
          image: demo-springmvc-app:v1
          ports:
            - containerPort: 8004
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"  # 设置环境变量，如激活 Spring Profile
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: demo-ee
spec:
  selector:
    app: demo-springmvc-app
  ports:
    - protocol: TCP
      port: 8304  #对外端口
      targetPort: 8004 #对内端口
  type: LoadBalancer  # 使用 LoadBalancer 类型的服务