spring:
  application:
    name: rocketmq-demo
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer-group
  consumer:
    group: consumer-group
  config:
    namesrvAddrs:
      - 127.0.0.1:8102
server:
  port: 8002