
server:
  #springboot启动端口
  port: 8001


#数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pms
    username: root
    password: dev123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  #dao层xml目录配置
  mapper-locations: com.mwt.ddd_demo_8001.domain.dao/*.mysql.xml


